version: 2
updates:
  # Maintain GitHub Actions dependencies
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: daily

  # Maintain JavaScript dependencies
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: daily
