version: 2
updates:
  # Maintain GitHub Actions dependencies
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    groups:
      actions:
        update-types: [minor, patch]

  # Maintain JavaScript dependencies
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: weekly
    groups:
      npm-development:
        dependency-type: development
        update-types: [minor, patch]
      npm-production:
        dependency-type: production
        update-types: [patch]
