changelog:
  categories:
    - title: ✨ Other Changes
      labels:
        - '*'
      exclude:
        labels:
          - dependencies
    - title: 🏗️ Dependencies
      labels:
        - dependencies
