name: regctl-installer
author: Kyle Colantonio
description: GitHub Action for installing the regctl CLI tool

branding:
  icon: package
  color: blue

inputs:
  regctl-release:
    description: regctl release version to be installed
    required: false
    default: latest
  verify:
    description: Perform signature verification on regctl
    required: false
    default: 'true'
  cache:
    description: Whether to utilize cache with regctl
    required: false
    default: 'true'
  token:
    description: GitHub token for REST API access
    required: false
    default: ${{ github.token }}

outputs:
  version:
    description: The version of regctl that was installed
  cache-hit:
    description: If regctl was installed via cache

runs:
  using: node20
  main: dist/index.js
