name: Action Test & Release

on:
  push:
    branches: [main]
    paths:
      - .github/workflows/main.yml
      - action.yml
  pull_request:
    branches: [main]
    paths:
      - .github/workflows/main.yml
      - action.yml

jobs:
  test:
    name: Test action
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]
        cosign: [true, false]

    steps:
      - name: Checkout repo
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7

      - name: Install Cosign
        uses: sigstore/cosign-installer@4959ce089c160fddf62f7b42464195ba1a56d382 # v3.6.0
        if: matrix.cosign

      - name: Install regctl
        uses: ./

      - name: Test regctl
        run: regctl version

  main:
    name: Publish new version
    if: github.event_name == 'push'
    needs: [test]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7

      - name: Bump version tag
        id: tag
        uses: mathieudutour/github-tag-action@a22cf08638b34d5badda920f9daf6e72c477b07b # v6.2
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Update shared tags
        run: |
          MAJOR=$(echo ${{ steps.tag.outputs.new_version }} | cut -d . -f 1)
          MINOR=$(echo ${{ steps.tag.outputs.new_version }} | cut -d . -f 2)
          git tag -f v$MAJOR
          git tag -f v$MAJOR.$MINOR
          git push -f -u origin v$MAJOR
          git push -f -u origin v$MAJOR.$MINOR

      - name: Create GitHub release
        uses: softprops/action-gh-release@c062e08bd532815e2082a85e87e3ef29c3e6d191 # v2.0.8
        with:
          tag_name: v${{ steps.tag.outputs.new_version }}
          make_latest: true
          generate_release_notes: true
