name: Shared Tags
run-name: ${{ github.ref_name }}

on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'

jobs:
  release:
    name: Update shared tags
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout repo
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Update tags
        shell: bash
        run: |
          MAJOR=$(cut -d '.' -f 1 <<< "$GITHUB_REF_NAME")
          MINOR=$(cut -d '.' -f 2 <<< "$GITHUB_REF_NAME")
          cat <<EOF
          VERSION=$GITHUB_REF_NAME
          MAJOR=$MAJOR
          MINOR=$MINOR
          EOF

          git tag -f "$MAJOR.$MINOR" "$GITHUB_SHA"
          git tag -f "$MAJOR" "$GITHUB_SHA"
          git push -u origin -f "$MAJOR.$MINOR"
          git push -u origin -f "$MAJOR"

          git show-ref --tags | grep "$GITHUB_SHA"
