name: Action Tests

on:
  workflow_dispatch:
  push:
    branches: [main]
    paths:
      - action.yml
  pull_request:
    branches: [main]
    paths:
      - action.yml

jobs:
  test:
    name: Test action
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]
        release: [latest, v0.7.1]
        cosign: [true, false]
        cache: [true, false]
    steps:
      - name: Checkout repo
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7

      - name: Install Cosign
        if: matrix.cosign == true
        uses: sigstore/cosign-installer@4959ce089c160fddf62f7b42464195ba1a56d382 # v3.6.0

      - name: Install regctl
        id: regctl
        uses: ./
        with:
          regctl-release: ${{ matrix.release }}
          cache: ${{ matrix.cache }}

      - name: Test regctl
        shell: bash
        env:
          VERSION: ${{ steps.regctl.outputs.version }}
        run: |
          regctl version | grep "$VERSION"
